name: Microservice

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # -------------------------
    # Setup .NET
    # -------------------------
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Clean MangoFusion API Backend
      run: dotnet clean Backend/MangoFusion.API.slnx

    - name: Restore MangoFusion API Backend
      run: dotnet restore Backend/MangoFusion.API.slnx

    - name: Build MangoFusion API Backend
      run: dotnet build --no-restore Backend/MangoFusion.API.slnx

    # -------------------------
    # Setup Node (for React)
    # -------------------------
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    # -------------------------
    # Install & Build React App
    # -------------------------
    - name: Install dependencies
      working-directory: Frontend/mangopedia
      run: npm install

    - name: Build React App
      working-directory: Frontend/mangopedia
      run: npm run build
